language: cpp
compiler:
  - gcc
# - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - build-essential
    - g++-5
    - clang-3.6
    - libboost1.55
cache:
  directories:
  - $HOME/cmake_temp
install:
# Set compiler versions to something modern
  - export TOOL_NAME=$CC
  - test $CC = gcc && export CC=gcc-5; export CXX=g++-5 || true
  - test $CC = clang && export CC=clang-3.6; export CXX=clang++-3.6 || true
  - $CC --version
# Install boost if it is not in cache
  - wget -O cmake.tar.gz http://www.cmake.org/files/v3.3/cmake-3.3.0-rc4-Linux-x86_64.tar.gz && mkdir cmake_temp && tar xf cmake.tar.gz -C cmake_temp --strip-components=1
script:
  - cmake_temp/bin/cmake .
  - make
# - make test
# As tests are in bad state now
